// eslint-disable-next-line
const projects = [
  {
    Name: "Docschat",
    Desc: "Docschat enables conversational interaction with documents using LLMs, along with integrated content retrieval capabilities.",
    type: "gen ai mern stack",
    Techs: ["LangChain", "MERN Stack", "Flask", "Nginx", "Redis"],
    Tools: ["VS Code", "Jupyter NB", "PowerShell", "Git"],
    Live: "https://docschat.in",
    href: "Live App",
    details: [],
  },
  {
    Name: "GNOST - Codebase Knowledge",
    Desc: "GNOST is a python package that helps understand unfamiliar codebases by automatically identifying entry points, execution flow, and core logic.",
    type: "pip package",
    Techs: ["Python", "pypi"],
    Tools: ["VS code", "Git"],
    Live: "https://pypi.org/project/gnost/",
    href: "View on PyPI",
    details: [],
  },
  {
    Name: "SurfMind",
    Desc: "SurfMind is a cutting-edge Chrome extension designed to enhance your browsing experience by intelligently tracking and managing the websites you visit",
    type: "gen ai chrome extension",
    Techs: ["LangChain", "React", "FastAPI", "Nginx"],
    Tools: ["VS Code", "Jupyter NB", "PowerShell", "Git"],
    Live: "https://surfmind.docschat.in",
    href: "Add To Chrome",
    details: [],
  },
];

const allprojects = [
  {
    Name: "GNOST - Codebase Knowledge",
    category: "python-package",
    type: "pip package",
    Desc: "GNOST is a python package that helps understand unfamiliar codebases by automatically identifying entry points, execution flow, and core logic.",
    Techs: ["python", "pypi"],
    Tools: ["VS code", "Git"],
    img: "gnost.png",
    button: [
      {
        name: "Details",
        link: "/projects/gnost",
        icon: "fa-solid fa-arrow-up-right-from-square",
        bg: "primary",
        ref: "_self",
      },
    ],
  },
  {
    Name: "Curlmin",
    category: "web-apps",
    type: "url shortener",
    Desc: "Built CurlMin, a URL shortening and management platform with support for QR codes, barcodes, and smart link sharing.",
    Techs: ["MERN Stack", "Nginx", "MySQL"],
    Tools: ["VS code", "PowerShell", "Git"],
    img: "curlmin.png",
    button: [
      {
        name: "Live App",
        link: "https://curlmin.com",
        icon: "fas fa-stream",
        bg: "danger",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "OpenClaw Spending Agent",
    category: "gen-ai",
    type: "agentic ai",
    Desc: "A personal AI agent that fetches Axis Bank transaction emails, categorizes spending with regex rules, generates HTML dashboards, and sends weekly WhatsApp summaries — triggerable on-demand via natural language.",
    Techs: ["Python", "SQLite", "OpenClaw", "Himalaya", "WhatsApp", "nginx"],
    Tools: ["VS Code", "Git"],
    img: "gnost.png",
    button: [
      {
        name: "Details",
        link: "/projects/axis-spending-openclaw",
        icon: "fa-solid fa-arrow-up-right-from-square",
        bg: "primary",
        ref: "_self",
      },
    ],
  },
  {
    Name: "Docschat",
    category: "gen-ai",
    type: "gen ai mern stack",
    Desc: "Docschat enables conversational interaction with documents using LLMs, along with integrated content retrieval capabilities.",
    Techs: ["LangChain", "MERN Stack", "Flask", "Nginx", "Redis"],
    Tools: ["VS Code", "Jupyter NB", "PowerShell", "Git"],
    img: "docschat.jpg",
    button: [
      {
        name: "Live App",
        link: "https://docschat.in",
        icon: "fas fa-stream",
        bg: "danger",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "SurfMind",
    category: "chrome-extensions",
    type: "gen ai",
    Desc: "SurfMind is a cutting-edge Chrome extension designed to enhance your browsing experience by intelligently tracking and managing the websites you visit",
    Techs: ["LangChain", "React", "FastAPI", "Nginx", "Redis"],
    Tools: ["VS Code", "Jupyter NB", "PowerShell", "Git"],
    img: "surfmind.jpg",
    button: [
      {
        name: "Add To Chrome",
        link: "https://chromewebstore.google.com/detail/surfmind/ladckalplikfcplbihpgfnlkonnpehkj",
        icon: "fas fa-stream",
        bg: "danger",
        ref: "_blank",
      },
      {
        name: "Details",
        link: "https://surfmind.docschat.in",
        icon: "fa-solid fa-arrow-up-right-from-square",
        bg: "primary",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "LexiClick",
    category: "chrome-extensions",
    type: "gen ai",
    Desc: "Built LexiClick, a Chrome extension for instant word definitions, synonyms, and AI-powered insights on double-click.",
    Techs: ["LangChain", "React", "Flask", "Nginx"],
    Tools: ["VS Code", "Jupyter NB", "PowerShell", "Git"],
    Live: "https://chromewebstore.google.com/detail/lexiclick/ffeidnombcpdibpkekekgfkaclhjbjpj",
    img: "instant.png",
    button: [
      {
        name: "Add To Chrome",
        link: "https://chromewebstore.google.com/detail/lexiclick/ffeidnombcpdibpkekekgfkaclhjbjpj",
        icon: "fas fa-stream",
        bg: "danger",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "Curlmin Chrome Extension",
    category: "chrome-extensions",
    type: "url shortener",
    Desc: "Built a Chrome extension for CurlMin to generate and save shortened URLs with a single click.",
    Techs: ["React", "Nginx"],
    Tools: ["VS Code", "PowerShell", "Git"],
    Live: "https://chromewebstore.google.com/detail/curlmin/nfgjgdpidaejbpnohadipbbikljiebbc",
    img: "curlmin_ce.jpg",
    button: [
      {
        name: "Add To Chrome",
        link: "https://chromewebstore.google.com/detail/curlmin/nfgjgdpidaejbpnohadipbbikljiebbc",
        icon: "fas fa-stream",
        bg: "danger",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "Car Sales Prediction",
    category: "machine-learning",
    type: "prediction",
    Desc: "Forecasted car sales using multivariate linear regression with SGD optimization and L2 regularization to improve generalization.",
    Techs: ["Pandas", "Sklearn"],
    Tools: ["Jupyter NB", "Git"],
    img: "csp.png",
    button: [
      {
        name: "Details",
        link: "https://old.mohdzain.com/projects/cars_sales_prediction.html",
        icon: "fa-solid fa-arrow-up-right-from-square",
        bg: "primary",
        ref: "_blank",
      },
      {
        name: "Github",
        link: "https://github.com/mohdzain98/applied-ml-projects/tree/main/car-sales-prediciton",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "Football Player Market Value Prediction",
    category: "machine-learning",
    type: "prediction",
    Desc: "Built an ANN model to predict football player values using mini-batch gradient descent and MSE loss.",
    Techs: ["Pandas", "Sklearn", "Keras"],
    Tools: ["Jupyter NB", "Git"],
    img: "fpmp.jpg",
    button: [
      {
        name: "Details",
        link: "https://old.mohdzain.com/projects/fpmvp.html",
        icon: "fa-solid fa-arrow-up-right-from-square",
        bg: "primary",
        ref: "_blank",
      },
      {
        name: "Github",
        link: "https://github.com/mohdzain98/applied-ml-projects/tree/main/football-player-market-value-prediction",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "NewsLookUp",
    category: "machine-learning",
    type: "classification",
    Desc: "News Reading app which fetches news from News API and render it in different categories. Machine Learning model is also used to analyse the Sentiment of News Headline",
    Techs: ["React", "Flask"],
    Tools: ["VS Code", "Jupyter NB", "Git"],
    img: "nlookup.jpg",
    button: [
      {
        name: "Github",
        link: "https://github.com/mohdzain98/newslookup",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "Skin Cancer Detection",
    category: "deep-learning",
    type: "classification",
    Desc: "Built a CNN model for skin lesion classification on ISIC data, achieving 80% accuracy. Used Binary Cross-Entropy loss and Adam optimization for training.",
    Techs: ["CNN", "Pandas", "Sklearn", "TensorFlow"],
    Tools: ["Jupyter NB", "Git"],
    img: "scd.webp",
    button: [
      {
        name: "Details",
        link: "https://old.mohdzain.com/projects/skin_cancer_detection.html",
        icon: "fa-solid fa-arrow-up-right-from-square",
        bg: "primary",
        ref: "_blank",
      },
      {
        name: "Github",
        link: "https://github.com/mohdzain98/applied-ml-projects/tree/main/skin-cancer-detection",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "Air Pollution Prediction",
    category: "deep-learning",
    type: "prediction",
    Desc: "Developed an LSTM-based model to forecast air pollution levels using historical data and MSE loss.",
    Techs: ["RNN", "LSTM", "Pandas", "Sklearn", "TensorFlow"],
    Tools: ["Jupyter NB", "Git"],
    img: "app.png",
    button: [
      {
        name: "Details",
        link: "https://old.mohdzain.com/projects/air_pollution_prediction.html",
        icon: "fa-solid fa-arrow-up-right-from-square",
        bg: "primary",
        ref: "_blank",
      },
      {
        name: "Github",
        link: "https://github.com/mohdzain98/applied-ml-projects/tree/main/air-pollution-prediction",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "Retail Price Optimization",
    category: "deep-learning",
    type: "prediction",
    Desc: "Built an ANN-based retail price optimization model to predict optimal pricing using historical demand data.",
    Techs: ["ANN", "Pandas", "Sklearn", "TensorFlow"],
    Tools: ["Jupyter NB", "Git"],
    img: "rpo.webp",
    button: [
      {
        name: "Details",
        link: "https://old.mohdzain.com/projects/retail_price_optimization.html",
        icon: "fa-solid fa-arrow-up-right-from-square",
        bg: "primary",
        ref: "_blank",
      },
      {
        name: "Github",
        link: "https://github.com/mohdzain98/Retail_price_optimization",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "NoteSwift",
    category: "web-apps",
    type: "mern stack",
    Desc: "Built a full-stack notes app with JWT-based authentication for secure, accessible data storage.",
    Techs: ["MERN Stack"],
    Tools: ["VS Code", "MongoDB Atlas", "Git", "Vercel"],
    img: "noteswift.webp",
    button: [
      {
        name: "Live App",
        link: "https://noteswift-pi.vercel.app/",
        icon: "fas fa-stream",
        bg: "danger",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "TechBooks",
    category: "web-apps",
    type: "JSP webapp",
    Desc: "Built a book recommendation website for engineering disciplines with direct purchase links to Amazon and Flipkart.",
    Techs: ["Java", "JSP", "HTML", "CSS", "MySQL", "Tomcat"],
    Tools: ["Netbeans", "Git", "AWS", "phpmyadmin"],
    img: "techbooks.jpg",
    button: [
      {
        name: "Github",
        link: "https://github.com/mohdzain98/techbooks",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "BracketsBay",
    category: "web-apps",
    type: "php webapp",
    Desc: "Designed an e-commerce website for curtain brackets with a clean UI and seamless user experience.",
    Techs: ["PHP", "HTML", "CSS", "MySQL"],
    Tools: ["Sublime Text", "Git", "phpmyadmin"],
    img: "bb.jpg",
    button: [
      {
        name: "Github",
        link: "https://github.com/mohdzain98/bracketsbay",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
];

export { projects, allprojects };
