flowchart TD
  src_pages_home_components_Careerpath_js --> src_components_layout_Ribbon_js
  src_pages_home_components_Skills_js --> src_components_Bars_ProgressBar_js
  src_pages_home_components_Exp_js --> src_config_allexp_js
  src_pages_home_Home_js --> src_pages_home_components_Intro_js
  src_pages_home_components_Research_js --> src_components_layout_Ribbon_js
  src_App_js --> src_pages_Gnost_js
  src_pages_home_Home_js --> src_pages_home_components_Skills_js
  src_App_js --> src_pages_Allprojects_js
  src_pages_home_components_Achivements_js --> src_components_layout_Ribbon_js
  src_pages_blogs_blogRegistry_js --> src_pages_blogs_tracing_TracingExample_js
  src_pages_home_Home_js --> src_pages_home_components_Social_js
  src_pages_Allprojects_js --> src_config_allproject_js
  src_App_js --> src_components_ui_Navbar_js
  src_pages_home_components_Skills2_js --> src_components_layout_Ribbon_js
  src_pages_home_Home_js --> src_pages_home_components_Careerpath_js
  src_pages_blogs_cryptosystem_CimagesCrypt_js --> src_pages_blogs_cryptosystem_Conclusion_js
  src_index_js --> src_reportWebVitals_js
  src_App_js --> src_components_Bars_Topbar_js
  src_pages_blogs_AllExample_js --> src_pages_blogs_blogRegistry_js
  src_pages_home_components_Skills_js --> src_components_Bars_CPBar_js
  src_pages_blogs_blogRegistry_js --> src_pages_blogs_cryptosystem_CimagesCrypt_js
  src_App_js --> src_pages_blogs_AllBlogs_js
  src_pages_blogs_tracing_LLMTracing_js --> src_components_layout_CodeBlock_js
  src_pages_home_Home_js --> src_pages_home_components_Achivements_js
  src_pages_blogs_AllBlogs_js --> src_pages_blogs_blogRegistry_js
  src_pages_home_Home_js --> src_pages_home_components_Skills2_js
  src_pages_blogs_cryptosystem_CimagesCrypt_js --> src_pages_blogs_cryptosystem_Results_js
  src_pages_blogs_cryptosystem_CimagesCrypt_js --> src_pages_blogs_cryptosystem_Encryption_js
  src_pages_blogs_cryptosystem_CimagesCrypt_js --> src_pages_blogs_cryptosystem_Decryption_js
  src_App_js --> src_pages_Blogs_js
  src_pages_home_components_Projects_js --> src_components_layout_Ribbon_js
  src_App_js --> src_pages_blogs_AllExample_js
  src_pages_home_components_Skills_js --> src_components_layout_Ribbon_js
  src_pages_Gitrepos_js --> src_config_allrepos_js
  src_pages_home_components_Intro_js --> src_components_layout_Ribbon_js
  src_App_js --> src_pages_home_Home_js
  src_pages_home_components_Exp_js --> src_components_layout_Ribbon_js
  src_pages_home_components_Skills_js --> src_components_Bars_SegmentedProgressBar_js
  src_index_js --> src_App_js
  src_pages_home_Home_js --> src_pages_home_components_Head_js
  src_pages_home_Home_js --> src_pages_home_components_Footer_js
  src_App_js --> src_pages_Gitrepos_js
  src_pages_home_Home_js --> src_pages_home_components_Exp_js
  src_pages_home_Home_js --> src_pages_home_components_Projects_js
  src_App_js --> src_components_ui_ScrollToTop_js
  src_pages_blogs_blogRegistry_js --> src_pages_blogs_tracing_LLMTracing_js
  src_pages_home_components_Projects_js --> src_config_allproject_js
  src_pages_home_Home_js --> src_pages_home_components_Research_js
  src_pages_blogs_cryptosystem_CimagesCrypt_js --> src_pages_blogs_cryptosystem_References_js
  src_pages_blogs_tracing_TracingExample_js --> src_components_layout_CodeBlock_js
  src_pages_Blogs_js --> src_pages_blogs_blogRegistry_js
  src_pages_home_components_Skills_js --> src_components_Bars_Vertical_js
  src_App_js --> src_pages_Wrong_js
  src_pages_home_components_Head_js --> src_components_layout_TypingEffect_js
