// eslint-disable-next-line
const projects = [
  {
    Name: "Curlmin",
    Desc: "Curlmin is an advanced URL shortening and management platform designed to make sharing links faster, smarter, and more efficient. Whether you need shortened URLs, QR codes, barcodes, or Curltags, Curlmin provides a seamless solution for individuals.",
    Techs: ["MERN Stack,", "Nginx,", "MySQL"],
    Tools: ["Git"],
    Live: "https://curlmin.com",
    href: "Live App",
    details: [],
  },
  {
    Name: "Docschat",
    Desc: "Docschat is an innovative project designed to revolutionize how users interact with documents. By leveraging the power of Large Language Models (LLMs), Docschat enables intuitive, conversational interactions with Documents. Additionally it contains content retrieval tools.",
    Techs: ["LangChain,", "MERN Stack,", "Python Flask,", "Nginx,", "Redis"],
    Tools: ["VS Code", "Jupyter NB", "PowerShell", "Git"],
    Live: "https://docschat.in",
    href: "Live App",
    details: [],
  },
  {
    Name: "LexiClick",
    Desc: " Instantly access definitions, examples, synonyms, and antonyms on double-click, plus AI-driven search for deeper insights",
    Techs: ["LangChain,", "React,", "Python Flask,", "Nginx"],
    Tools: ["VS Code", "Jupyter NB", "PowerShell", "Git"],
    Live: "https://chromewebstore.google.com/detail/lexiclick/ffeidnombcpdibpkekekgfkaclhjbjpj",
    href: "Add To Chrome",
    details: [],
  },
  {
    Name: "SurfMind",
    Desc: "SurfMind is a cutting-edge Chrome extension designed to enhance your browsing experience by intelligently tracking and managing the websites you visit",
    Techs: ["LangChain,", "React,", "Python Flask,", "Nginx"],
    Tools: ["VS Code", "Jupyter NB", "PowerShell", "Git"],
    Live: "https://chromewebstore.google.com/detail/surfmind/ladckalplikfcplbihpgfnlkonnpehkj",
    href: "Add To Chrome",
    details: [],
  },
];

const allprojects = [
  {
    Name: "Curlmin",
    Desc: "Curlmin is an advanced URL shortening and management platform designed to make sharing links faster, smarter, and more efficient. Whether you need shortened URLs, QR codes, barcodes, or Curltags, Curlmin provides a seamless solution for individuals.",
    Techs: ["MERN Stack,", "Nginx,", "MySQL"],
    Tools: ["VS code", "PowerShell", "Git"],
    img: "curlmin.png",
    button: [
      {
        name: "Live App",
        link: "https://curlmin.com",
        icon: "fas fa-stream",
        bg: "danger",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "Docschat",
    Desc: "Docschat is an innovative project designed to revolutionize how users interact with documents. By leveraging the power of Large Language Models (LLMs), Docschat enables intuitive, conversational interactions with Documents. Additionally it contains content retrieval tools.",
    Techs: ["LangChain,", "MERN Stack,", "Python Flask,", "Nginx,", "Redis"],
    Tools: ["VS Code", "Jupyter NB", "PowerShell", "Git"],
    img: "docschat.jpg",
    button: [
      {
        name: "Live App",
        link: "https://docschat.in",
        icon: "fas fa-stream",
        bg: "danger",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "Curlmin Chrome Extension",
    Desc: " Curlmin Chrome Extension simplifies URL shortening with a single click. Quickly generate short links and save them to your CurlMin account for easy access. Fast, seamless, and efficient!",
    Techs: ["React,", "Nginx"],
    Tools: ["VS Code", "PowerShell", "Git"],
    Live: "https://chromewebstore.google.com/detail/curlmin/nfgjgdpidaejbpnohadipbbikljiebbc",
    img: "curlmin_ce.jpg",
    button: [
      {
        name: "Add To Chrome",
        link: "https://chromewebstore.google.com/detail/curlmin/nfgjgdpidaejbpnohadipbbikljiebbc",
        icon: "fas fa-stream",
        bg: "danger",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "LexiClick",
    Desc: " Elevate your reading experience with LexiClick, the intelligent Chrome extension that brings instant access to word definitions, examples, synonyms, and antonyms with just a double-click, plus AI-driven search for deeper insights",
    Techs: ["LangChain,", "React,", "Python Flask,", "Nginx"],
    Tools: ["VS Code", "Jupyter NB", "PowerShell", "Git"],
    Live: "https://chromewebstore.google.com/detail/lexiclick/ffeidnombcpdibpkekekgfkaclhjbjpj",
    img: "instant.png",
    button: [
      {
        name: "Add To Chrome",
        link: "https://chromewebstore.google.com/detail/lexiclick/ffeidnombcpdibpkekekgfkaclhjbjpj",
        icon: "fas fa-stream",
        bg: "danger",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "SurfMind",
    Desc: "SurfMind is a cutting-edge Chrome extension designed to enhance your browsing experience by intelligently tracking and managing the websites you visit",
    Techs: ["LangChain,", "React,", "Python Flask,", "Nginx"],
    Tools: ["VS Code", "Jupyter NB", "PowerShell", "Git"],
    img: "surfmind.jpg",
    button: [
      {
        name: "Add To Chrome",
        link: "https://chromewebstore.google.com/detail/surfmind/ladckalplikfcplbihpgfnlkonnpehkj",
        icon: "fas fa-stream",
        bg: "danger",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "Car Sales Prediction",
    Desc: "Employed a Machine Learning approach to forecast car sales using Multivariate Linear Regression with Stochastic Gradient Descent (SGD) and L2 Regularization. Updated model weights iteratively with SGD to minimize the loss function and applied L2 Regularization to prevent overfitting by penalizing large coefficients",
    Techs: ["Python,", "Pandas,", "Sklearn"],
    Tools: ["Jupyter NB", "Git"],
    img: "csp.png",
    button: [
      {
        name: "Details",
        link: "https://old.mohdzain.com/projects/cars_sales_prediction.html",
        icon: "fa-solid fa-circle-info",
        bg: "primary",
        ref: "_blank",
      },
      {
        name: "Github",
        link: "https://github.com/mohdzain98/Car_Sales_Prediciton",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "Football Player Market Value Prediction",
    Desc: "Implemented an Artificial Neural Network on an extensive dataset of football player values from 2021 to train models for accurately predicting player values. Used Mini Batch Gradient Descent for weight updates and Mean Squared Error (MSE) as the loss function",
    Techs: ["Python,", "Pandas,", "Sklearn,", "Keras"],
    Tools: ["Jupyter NB", "Git"],
    img: "fpmp.jpg",
    button: [
      {
        name: "Details",
        link: "https://old.mohdzain.com/projects/fpmvp.html",
        icon: "fa-solid fa-circle-info",
        bg: "primary",
        ref: "_blank",
      },
      {
        name: "Github",
        link: "https://github.com/mohdzain98/Football-Player-s-Market_value_Prediction",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "NewsLookUp",
    Desc: "News Reading app which fetches news from News API and render it in different categories. Machine Learning model is also used to analyse the Sentiment of News Headline",
    Techs: ["Python,", "React,", "Flask"],
    Tools: ["VS Code", "Jupyter NB", "Git"],
    img: "nlookup.jpg",
    button: [
      {
        name: "Github",
        link: "https://github.com/mohdzain98/newslookup",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "Skin Cancer Detection",
    Desc: "Engineered a project applying a Convolutional Neural Network (CNN) to analyze skin lesion images from ISIC. Successfully classified images with 80% accuracy using the binary cross-entropy loss function",
    Techs: ["CNN,", "Python,", "Pandas,", "Sklearn,", "TensorFlow"],
    Tools: ["Jupyter NB", "Git"],
    img: "scd.webp",
    button: [
      {
        name: "Details",
        link: "https://old.mohdzain.com/projects/skin_cancer_detection.html",
        icon: "fa-solid fa-circle-info",
        bg: "primary",
        ref: "_blank",
      },
      {
        name: "Github",
        link: "https://github.com/mohdzain98/Skin_Cancer_Detection",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "Air Pollution Prediction",
    Desc: "Developed an air pollution prediction model utilizing Recurrent Neural Networks (RNN) with Long Short-Term Memory (LSTM) units. Accurately forecasted pollution levels with a mean squared error loss function, achieving reliable predictions based on historical air quality data.",
    Techs: ["RNN,", "LSTM,", "Python,", "Pandas,", "Sklearn,", "TensorFlow"],
    Tools: ["Jupyter NB", "Git"],
    img: "app.png",
    button: [
      {
        name: "Details",
        link: "https://old.mohdzain.com/projects/air_pollution_prediction.html",
        icon: "fa-solid fa-circle-info",
        bg: "primary",
        ref: "_blank",
      },
      {
        name: "Github",
        link: "https://github.com/mohdzain98/Air_Pollution_Prediction",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "Retail Price Optimization",
    Desc: "Implemented a retail price optimization system using an Artificial Neural Network (ANN) to predict optimal pricing strategies. Achieved accurate price predictions with a mean squared error (MSE) loss function, driving improved sales performance based on historical pricing and demand data.",
    Techs: ["ANN,", "Python,", "Pandas,", "Sklearn,", "TensorFlow"],
    Tools: ["Jupyter NB", "Git"],
    img: "rpo.webp",
    button: [
      {
        name: "Details",
        link: "https://old.mohdzain.com/projects/retail_price_optimization.html",
        icon: "fa-solid fa-circle-info",
        bg: "primary",
        ref: "_blank",
      },
      {
        name: "Github",
        link: "https://github.com/mohdzain98/Retail_price_optimization",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "NoteSwift",
    Desc: "Developed a full stack web app to save the notes of users on the web which can be accessed from anywhere. Implemented secure user authentication through JWT, ensuring data integrity and user privacy.",
    Techs: ["MERN Stack"],
    Tools: ["VS Code", "MongoDB Atlas", "Git", "Vercel"],
    img: "noteswift.webp",
    button: [
      {
        name: "Live App",
        link: "https://noteswift-pi.vercel.app/",
        icon: "fas fa-stream",
        bg: "danger",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "TechBooks",
    Desc: "Simple book website that lists the recommended books for all subjects in the engineering disciplines CSE, ECE, EE, MECH, and CIVIL. It will also include links to buy the respective book from Amazon and Flipcart.",
    Techs: ["Java,", "JSP,", "HTML,", "CSS,", "MySQL,", "Nginx,", "Tomcat"],
    Tools: ["Netbeans", "Git", "AWS", "phpmyadmin"],
    img: "techbooks.jpg",
    button: [
      {
        name: "Github",
        link: "https://github.com/mohdzain98/techbooks",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
  {
    Name: "BracketsBay",
    Desc: "I have conceptualized and designed an e-commerce website specializing in curtain brackets. This online platform showcases an extensive range of premium curtain bracket solutions, catering to diverse customer needs and design preferencesThe website combines sleek design with user-friendly navigation, ensuring a seamless shopping experience for visitors",
    Techs: ["PHP,", "HTML,", "CSS,", "MySQL,", "Nginx"],
    Tools: ["Sublime Text", "Git", "phpmyadmin"],
    img: "bb.jpg",
    button: [
      {
        name: "Github",
        link: "https://github.com/mohdzain98/bracketsbay",
        icon: "fa-brands fa-github",
        bg: "dark",
        ref: "_blank",
      },
    ],
  },
];

export { projects, allprojects };
